- name: Copy role files
  copy:
    src: "{{ playbook_dir }}/../{{ item }}"
    dest: /home/{{ ansible_user }}/{{ item }}
  with_items: "{{ group_names }}"

- name: build docker image(s)
  become: yes
  shell: |
    cd /home/{{ ansible_user }}/{{ item }}
    docker build -t {{ item }} .
  with_items: "{{ group_names }}"

- name: run docker container(s)
  become: yes
  shell: |
    docker run --restart always -d -p 80:8080 {{ item }}
  with_items: "{{ group_names }}"