- name: install firewall
  become: yes
  apt:
    name: ufw
    state: present

- name: enable firewall on exposed ports
  become: yes
  shell: ufw allow {{ app_port }}/tcp

#- name: Copy role files
#  copy:
#    src: "{{ playbook_dir }}/../{{ item }}"
#    dest: /home/{{ ansible_user }}/
#  with_items: "{{ group_names }}"

#- name: build docker image(s)
#  become: yes
#  shell: >-
#    cd /home/{{ ansible_user }}/{{ item }} && 
#    docker build -t {{ item }} .
#  with_items: "{{ group_names }}"
