
- name: create nginx backends config
  become: yes
  template:
    src: backends.conf.j2
    dest: /home/{{ ansible_user }}/backends.conf

- name: remove existing docker container(s)
  become: yes
  shell: >-
    docker stop dce_load_balancer &&
    docker rm -f dce_load_balancer &&
    docker rmi -f ghcr.io/justscrub/kiv-dce_load-balancer:latest
  ignore_errors: yes

- name: run docker container(s)
  become: yes
  shell: >-
    docker run 
    --restart always 
    --name dce_load_balancer 
    -v /home/{{ ansible_user }}/backends.conf:/etc/nginx/conf.d/backend-upstream.conf
    -d -p {{ app_port }}:80 ghcr.io/justscrub/kiv-dce_load-balancer:latest
  ignore_errors: yes